### PR TITLE
Add RedirectHandlerModule to required module

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
ping @Stanimirdim92  ;)

**Comment by samsonasik** [comment]
merge-able ? 💃

**Comment by Stanimirdim92** [comment]
Will check tonight. Havnt got time lately for this project.

На 26.10.2016 06:51 "Abdul Malik Ikhsan" <notifications@github.com> написа:

**Comment by samsonasik** [comment]
travis using composer install, seems need to update composer.lock file ?

**Comment by samsonasik** [comment]
I've updated composer.lock file

**Comment by Stanimirdim92** [comment]
ping @samsonasik Please, re-run the tests. :)

**Comment by samsonasik** [comment]
@Stanimirdim92 rebased, should be ok now 💃

**Comment by samsonasik** [comment]
merge-able ? :D

**Comment by Stanimirdim92** [comment]
Haven't tried, but I will in the next week. Working over something else
that needs my full attention.

2016-11-05 14:45 GMT+02:00 Abdul Malik Ikhsan <notifications@github.com>:

**Comment by Stanimirdim92** [comment]
Merging. Mnually fixed conflicts.

**Pull request merged**
